# -*- coding: utf-8 -*-
"""SPASELists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyFlZ_2fCilqhoJVt0EHPQ_i2Mj0Rpqw

Code used to extract the full list of links for the SPASE Lists.
"""

from pprint import pprint

import requests
import re

doc_id = '1RXSE2p4KEqB4ikUqvQd5AtLcvrqprbVlDmkSyBcS4zk'
# Construct the export URL for plain text
doc_url = f'https://docs.google.com/document/d/{doc_id}/export?format=txt'

try:
    response = requests.get(doc_url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    doc_content = response.text

    # Updated Regular expression to find URLs, matching until a newline or carriage return
    # This regex captures http/https followed by '://' and then any character that is not a newline or carriage return
    urls = re.findall(r'https?://[^\r\n]+', doc_content)

    if urls:
        print("Found the following links:")
        for url in urls:
            print(url)
        print(f"\nTotal {len(urls)} links found.") # Added print statement for the total count
    else:
        print("No links found in the document.")

except requests.exceptions.RequestException as e:
    print(f"Error accessing the Google Doc: {e}")
    print("Please ensure the document is published to web or has appropriate sharing settings.")

"""Extracts the list name. Later, use this to iterate for all the list names or just run one at a time.

"""

i=1
if urls:
    first_url = urls[i]
    # Extract the part after '#' if it exists
    if '#' in first_url:
        list_name = first_url.split('#')[-1]
        print(f"\nList name found: {list_name}")
        print(f"\nPosition number: {i}")
    else:
        print("\nNo list name (text after '#') found in the  URL.")
else:
    print("\nNo URLs were found to extract a list name.")

"""This extracts the JSON for easier manipulation and inspection."""

import requests
import json

json_url = 'https://spase-group.org/data/model/spase-latest.json'

try:
    response = requests.get(json_url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    json_data = response.json()
    print("JSON data extracted successfully!")
    # You can now work with 'json_data'
    # For example, to print the first few keys:
    # print(json.dumps(json_data, indent=2))

except requests.exceptions.RequestException as e:
    print(f"Error accessing the JSON data: {e}")
except json.JSONDecodeError as e:
    print(f"Error decoding JSON: {e}")

def extract_definitions(list_name, specific_list_data, dictionary_data):
    """
    Extracts and prints definitions for values in a given list from the dictionary data.
    Returns True if any individual allowedValue has a definition, False otherwise.

    Args:
        list_name (str): The name of the list being processed.
        specific_list_data (dict): Dictionary containing 'allowedValues' and its own 'definition'.
        dictionary_data (dict): The main dictionary containing definitions.
    """
    has_individual_definitions = False
    output_lines = []

    if 'allowedValues' in specific_list_data and isinstance(specific_list_data['allowedValues'], list):
        list_definition = specific_list_data.get('definition', 'No overall list definition found.')
        output_lines.append(f"\n--- Definitions for '{list_name}' ---")
        output_lines.append(f"Overall list definition: {list_definition}")
        output_lines.append(f"\nIndividual value descriptions within '{list_name}':")

        for value in specific_list_data['allowedValues']:
            if value in dictionary_data:
                definition = dictionary_data[value].get('definition', None)
                if definition:
                    output_lines.append(f"  - {value}: {definition}")
                    has_individual_definitions = True
                else:
                    output_lines.append(f"  - {value}: No 'definition' key found in its dictionary entry.")
            else:
                output_lines.append(f"  - {value}: No specific entry in the main dictionary.")
    else:
        output_lines.append(f"'allowedValues' not found or is not a list in the data for '{list_name}'.")

    if has_individual_definitions:
        for line in output_lines:
            print(line)
    return has_individual_definitions

"""Extracts the names in the indicated enumeration list."""

cleaned_list_name = list_name.strip()

if 'dictionary' in json_data and isinstance(json_data['dictionary'], dict):
    dictionary_data = json_data['dictionary']
    if cleaned_list_name in dictionary_data:
        specific_list_data = dictionary_data[cleaned_list_name]
        print(f"Keys for '{cleaned_list_name}':")
        print(specific_list_data['allowedValues'])
    else:
        print(f"'{cleaned_list_name}' not found within the 'dictionary' section.")
else:
    print("'dictionary' key not found or is not a dictionary in the JSON data.")

"""Extract the definitions for the names listed in specific_list_data['allowedValues'] from the json ('dictionary'?).

Now, let's extract the definition for the enumeration list name and store it in a separate dictionary.
"""

list_definition_dict = {}

# Ensure cleaned_list_name is available from previous cells
# Ensure json_data is available from previous cells

if 'cleaned_list_name' in globals() and cleaned_list_name:
    if 'dictionary' in json_data and isinstance(json_data['dictionary'], dict):
        dictionary_data = json_data['dictionary']
        if cleaned_list_name in dictionary_data:
            list_overall_data = dictionary_data[cleaned_list_name]
            definition = list_overall_data.get('definition', 'No definition found for this list.')
            list_definition_dict[cleaned_list_name] = definition
            print(f"Extracted definition for '{cleaned_list_name}': {definition}")
        else:
            print(f"'{cleaned_list_name}' not found in the main dictionary.")
    else:
        print("'dictionary' key not found or is not a dictionary in the JSON data.")
else:
    print("No cleaned list name available from previous steps.")

print("\n--- List Definition Dictionary ---")
print(list_definition_dict)

"""### Filtered List Definitions

Now, let's retrieve the definitions from the chosen enumeration list.
"""

print("Processing specific list to find individual allowedValue definitions...")

# Use the list_name from the previous cell
list_name_to_process = cleaned_list_name # Assuming cleaned_list_name from cell b3af1c5d is available and correctly set

definitions_dict = {}

if list_name_to_process:
    if 'dictionary' in json_data and isinstance(json_data['dictionary'], dict):
        dictionary_data = json_data['dictionary']
        if list_name_to_process in dictionary_data:
            specific_list_data = dictionary_data[list_name_to_process]

            # Extract the allowedValues directly
            allowed_values = specific_list_data.get('allowedValues', [])

            if allowed_values:
                print(f"\n--- Definitions for individual values in '{list_name_to_process}' ---")
                found_individual_definitions = False
                for value in allowed_values:
                    if value in dictionary_data:
                        definition = dictionary_data[value].get('definition', None)
                        if definition:
                            print(f"  - {value}: {definition}")
                            definitions_dict[value] = definition
                            found_individual_definitions = True
                        else:
                            print(f"  - {value}: No 'definition' key found in its dictionary entry.")
                    else:
                        print(f"  - {value}: No specific entry in the main dictionary.")

                if not found_individual_definitions:
                    print("No individual definitions found for allowed values.")
            else:
                print(f"No 'allowedValues' found for '{list_name_to_process}'.")
        else:
            print(f"'{list_name_to_process}' not found in the main dictionary.")
    else:
        print("'dictionary' key not found or is not a dictionary in the JSON data.")
else:
    print("No list name provided for processing.")

# Display the created dictionary
if definitions_dict:
    print("\n--- Extracted Definitions Dictionary ---")
    print(definitions_dict)
else:
    print("\nNo definitions were extracted to form a dictionary.")



"""### Generate JSON-LD for a List

Now, let's create JSON-LD (JSON for Linking Data) for one of the lists, 'AccessRights', using the definitions we've extracted. JSON-LD helps structure data on the web for better machine readability and search engine optimization, linking it to well-known vocabularies like schema.org. This will mimic the style of the `AccessRights.json` example provided, with 'Isabella Ruiz' as the author.
"""

import json
import requests

# Define the chosen list name (already available from previous cells)
chosen_list_name = cleaned_list_name

# Retrieve data for the chosen list
list_json_ld = {}

# Use the already extracted list_definition_dict for overall list definition
overall_definition = list_definition_dict.get(chosen_list_name, 'No overall list definition found.')

# Use the already extracted definitions_dict for individual allowed values and their definitions
allowed_values_and_definitions = definitions_dict

# Define the base ID for the ConceptScheme
concept_scheme_id = f"https://spase-group.org/data/model/spase-latest/skos/{chosen_list_name}"

# Prepare the JSON-LD for the overall list using SKOS vocabulary
list_json_ld = {
    "@context": {
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "dct": "http://purl.org/dc/terms/", # Added for creator mapping
        "Concept": { "@id": "skos:Concept" },
        "ConceptScheme": { "@id": "skos:ConceptScheme" }, # Modified to map to skos:ConceptScheme
        "title": { "@id": "skos:prefLabel" },  # Map 'title' to 'skos:prefLabel'
        "description": { "@id": "skos:definition" }, # Map 'description' to 'skos:definition'
        "creator": { "@id": "dct:creator" }, # Map 'creator' to 'dct:creator'
        "prefLabel": { "@id": "skos:prefLabel" }, # Kept for concepts within hasTopConcept
        "definition": { "@id": "skos:definition" }, # Kept for concepts within hasTopConcept
        "inScheme": { "@id": "skos:inScheme" }
    },
    "@graph": [ # Start of the @graph array
        {
            "@id": concept_scheme_id,
            "@type": "ConceptScheme", # This will resolve to skos:ConceptScheme via @context
            "title": chosen_list_name, # Using 'title' as per user example
            "description": overall_definition, # Using 'description' as per user example
            "creator": "Isabella Ruiz"
        }
    ]
}

# Add each allowedValue as a skos:Concept
# Append to the hasTopConcept list within the first item of the @graph array
for value, individual_definition in allowed_values_and_definitions.items():
    concept_id = f"{concept_scheme_id}/{value}"

    list_json_ld["@graph"].append({
        "@type": "Concept", # This will resolve to skos:Concept via @context
        "prefLabel": value, # Uses the 'prefLabel' mapping from context
        "definition": individual_definition, # Uses the 'definition' mapping from context
        "inScheme": concept_scheme_id # Link back to the concept scheme
    })

print(json.dumps(list_json_ld, indent=2))

"""Now we want to the json printed to a text file named for the list."""

import json

# Construct the filename
filename = f"{cleaned_list_name}.json"

# Write the JSON-LD to the file
with open(filename, 'w') as f:
    json.dump(list_json_ld, f, indent=2)

print(f"JSON-LD saved to {filename}")

from google.colab import files

files.download(filename)